language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:travis"
rvm:
  - 1.9.3
  - 2.1.1
  - rbx-2.1.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-2.1.1
    - rvm: ruby-head
notifications:
  email:
    recipients: bjorn.skarner@it.cdon.com
    on_success: never
    on_failure: change